- name: Install mysql database
  yum: 
    name: ["mysql-server", "mysql-client"] 
    state: present

- name: start mysql service
  service: 
    name: mysql
    state: started
    enabled: yes

- name: create application database
  mysql_db: 
    name: "{{ db_name }}" 
    state: present
    
- name: create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'