- name: Install  mariadb database
  yum: 
    name: ["maridb-server", "mariadb-client"] 
    state: present

- name: start mariadb service
  service: 
    name:  mariadb
    state: started
    enabled: yes

- name: create application database
  mysql_db: 
    name: "{{ db_name }}" 
    state: present
    
- name: create database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL'
    state: present
    host: '%'