# simple configuration file for web server
- name: Installation of web server
  hosts: all
  become: yes
  become_method: sudo
  become_user: ansiadmin
  roles:
    - web_role
    

- name: Installation of DB server
  hosts: all
  become: yes
  become_method: sudo
  become_user: mariadb
  roles:
    - db_role
 

